baseurl = "https://marae22.github.io"
languageCode = "en-us"
title = "Jessica Mccullough"
theme = "jessica-theme"
googleAnalytics = ""
publishDir = "../website"
[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Jessica"
	description = "Best Designer Ever"

	# The path must be relative to the static folder
	favicon = "logo.png"


	# Navigation
	[params.navigation]
		brand = "logo.png"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "My Projects"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "UX JESSICA"
		subtitle   = "DESIGNER // ARTIST // CODER"
		buttonText = "View my projects"
		buttonT = "Click for more"


	# About section
	[params.about]
		headline    = "MY PROJECTS"
		description = "Here are my recent projects."
		buttonText  = "View all projects"
		buttonT = "TEST"


	# #Service section
	# [params.services]
	# 	headline = "Programs I Use"
  #       [[params.services.list]]
  #           icon = "fa-diamond"
  #           title = "Sketch"
  #           description = "I use Sketch to create and refine lo-fidelity and hi-fidelity mockups."
	#
  #       [[params.services.list]]
	# 		icon = "fa-paper-plane"
	# 		title = "Flinto"
	# 		description = "I use Flinto to show what can be done with my designs."
	#
	# 	[[params.services.list]]
  #           icon = "fa-html5"
  #           title = "HTML"
  #           description = "I use HTML to frame my designs."
	#
  #       [[params.services.list]]
  #           icon = "fa-css3"
  #           title = "CSS"
  #           description = "I use CSS to bring my designs to life."

    # Portfolio modals
	[params.portfolio.modal]
        client = "tset"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Want to know more about my background?"

		[params.aside.button]
			text = "Download Resume"
			link = "/pdf/jessicamcculloughresume.pdf"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with me? That's great! Give me a call or send me an email and I will get back to you as soon as possible!"
		phone = "707-834-7401"
		email = "uxjessica1@gmail.com"
		linkedin = "linkedin.com/in/jessica-mcccullough1"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
