baseurl = "https://example.org/"
languageCode = "en-us"
title = "Hugo Creative Theme"
theme = "hugo-creative-theme"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Jessica"
	description = "Best Designer Ever"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Uxj"

		[params.navigation.links]
			about     = "About"
			services  = "Services"
			portfolio = "Portfolio"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		slogan     = "Uxj"
		subtitle   = "I have known my whole life that I can draw a picture and balance a check book but I didn’t know that it would lead me to where I am today..."
		buttonText = "View my projects"
		buttonT = "Click for more"


	# About section
	[params.about]
		headline    = "My Projects"
		description = "Here are my recent projects"
		links = "http://localhost:1313/project/sfbc/"
		link2 = "http://localhost:1313/project/earn-org/"
		buttonText  = "MORE!"
		buttonT = "TEST"


	# Service section
	# [params.services]
	# 	headline = "Programs I Use"
  #       [[params.services.list]]
  #           icon = "fa-diamond"
  #           title = "Sketch"
  #           description = "I use Sketch to create and refine lo-fidelity and hi-fidelity mockups."
	#
  #       [[params.services.list]]
	# 		icon = "fa-paper-plane"
	# 		title = "Flinto"
	# 		description = "I use Flinto to show what can be done with my designs."
	#
	# 	[[params.services.list]]
  #           icon = "fa-html5"
  #           title = "HTML"
  #           description = "I use HTML to frame my designs."
	#
  #       [[params.services.list]]
  #           icon = "fa-css3"
  #           title = "CSS"
  #           description = "I use CSS to bring my designs to life."


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Want to view my resume?"

		[params.aside.button]
			text = "View now"
			link = "http://uxjessica.me/resume/"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with me? That's great! Give me a call or send me an email and I will get back to you as soon as possible!"
		phone = "707-834-7401"
		email = "uxjessica1@gmail.com"
		linkedin = "linkedin.com/in/jessica-mcccullough1"

	# Google Maps section
	# [params.location]
	# 	latitude  = "34.007850"
	# 	longitude = "-118.499305"
	# 	maps_api_key = ""
